# Generated by Django 6.0.4 on 2026-05-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='watchlist',
            field=models.JSONField(default=list),
        ),
    ]
