# Generated by Django 6.0.4 on 2026-05-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liked_movies',
            field=models.JSONField(default=list),
        ),
    ]
