# Generated by Django 6.0.4 on 2026-05-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_liked_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.CharField(default='https://images.7tv.app/01GK9P0Z5G00085G5Z1YV7C0Y8/2x.webp', max_length=500),
        ),
    ]
