# Generated by Django 6.0.4 on 2026-05-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.CharField(default='/images/avatars/avatar_popcorn.png', max_length=500),
        ),
    ]
